/**
 * Component: Change Meta File Processor
 * Block-UUID: 85d9185d-da58-4678-bcb1-bc0e2a3a08ea
 * Parent-UUID: 6b404acf-d50d-4562-bacd-81737ee22fd0
 * Version: 1.9.0
 * Description: Processes .change-meta.json files generated by AI during change turns, validates them, builds aggregated changelog, and manages cleanup. Added WriteChangeMetadataJSONL to aggregate metadata into a turn-local JSONL file before cleanup for resumption support. Updated ProcessChangeMetaFiles to copy NewVersion and OldVersion from GSCFileData to ChangelogEntry to ensure version history is preserved in result.json.
 * Language: Go
 * Created-at: 2026-04-25T12:47:22.658Z
 * Authors: GLM-4.7 (v1.0.0), GLM-4.7 (v1.1.0), GLM-4.7 (v1.2.0), GLM-4.7 (v1.3.0), GLM-4.7 (v1.4.0), GLM-4.7 (v1.5.0), GLM-4.7 (v1.5.1), Gemini 2.5 Flash Lite (v1.6.0), Gemini 3 Flash (v1.7.0), GLM-4.7 (v1.8.0), Gemini 3 Flash (v1.9.0)
 */


package intent_workflow

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// FindChangeMetaFiles finds all .change-meta.json files in the working directories
func FindChangeMetaFiles(workingDirs []WorkingDirectory) ([]string, error) {
	var metaFiles []string

	for _, wd := range workingDirs {
		err := filepath.Walk(wd.Path, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}

			// Skip directories
			if info.IsDir() {
				return nil
			}

			// Check if file matches .change-meta.json pattern
			if strings.HasSuffix(info.Name(), ".change-meta.json") {
				metaFiles = append(metaFiles, path)
			}

			return nil
		})

		if err != nil {
			return nil, fmt.Errorf("failed to scan workdir %s: %w", wd.Path, err)
		}
	}

	return metaFiles, nil
}

// readAndParseMetaFile reads a .change-meta.json file, strips markdown fences (Forgiving Parser),
// and unmarshals it into a GSCFileData struct.
func readAndParseMetaFile(metaFilePath string) (*GSCFileData, error) {
	// Read .change-meta.json file
	data, err := os.ReadFile(metaFilePath)
	if err != nil {
		return nil, fmt.Errorf("failed to read %s: %w", metaFilePath, err)
	}

	// Strip markdown code fences and whitespace (Forgiving Parser)
	content := strings.TrimSpace(string(data))
	if strings.HasPrefix(content, "```json") {
		content = strings.TrimPrefix(content, "```json")
		content = strings.TrimSpace(content)
	} else if strings.HasPrefix(content, "```") {
		content = strings.TrimPrefix(content, "```")
		content = strings.TrimSpace(content)
	}
	if strings.HasSuffix(content, "```") {
		content = strings.TrimSuffix(content, "```")
		content = strings.TrimSpace(content)
	}

	// Parse JSON
	var gscData GSCFileData
	if err := json.Unmarshal([]byte(content), &gscData); err != nil {
		return nil, fmt.Errorf("failed to parse %s: %w", metaFilePath, err)
	}

	return &gscData, nil
}

// ProcessChangeMetaFiles reads .change-meta.json files and builds aggregated changelog
func ProcessChangeMetaFiles(metaFiles []string) ([]ChangelogEntry, error) {
	var changelog []ChangelogEntry

	for _, metaFilePath := range metaFiles {
		gscData, err := readAndParseMetaFile(metaFilePath)
		if err != nil {
			return nil, err
		}

		// Validate required fields
		if gscData.AbsolutePath == "" {
			return nil, fmt.Errorf("missing absolute_path in %s", metaFilePath)
		}
		if gscData.Description == "" {
			return nil, fmt.Errorf("missing description in %s", metaFilePath)
		}
		if gscData.ChangeType == "" {
			return nil, fmt.Errorf("missing change_type in %s (enrichment may not have run)", metaFilePath)
		}

		// Validate change_type
		validChangeTypes := map[string]bool{
			"modified": true,
			"added":    true,
			"deleted":  true,
			"renamed":  true,
		}
		if !validChangeTypes[gscData.ChangeType] {
			return nil, fmt.Errorf("invalid change_type '%s' in %s", gscData.ChangeType, metaFilePath)
		}

		// Validate NewBlobSHA is present for non-deleted files
		if gscData.ChangeType != "deleted" && gscData.NewBlobSHA == "" {
			return nil, fmt.Errorf("missing new_blob_sha in %s (enrichment may not have run)", metaFilePath)
		}

		// Add to changelog
		changelog = append(changelog, ChangelogEntry{
			File:        gscData.AbsolutePath,
			ChangeType:  gscData.ChangeType,
			Description: gscData.Description,
			NewVersion:  gscData.NewVersion,
			OldVersion:  gscData.OldVersion,
			OldBlobSHA:  gscData.OldBlobSHA,
			NewBlobSHA:  gscData.NewBlobSHA,
			Language:    gscData.Language,
		})
	}

	return changelog, nil
}

// WriteChangeMetadataJSONL aggregates all .change-meta.json files into a single JSONL file
// in the turn directory. This preserves the metadata for resumption without cluttering
// the working directory.
func WriteChangeMetadataJSONL(metaFiles []string, turnDir string) error {
	jsonlPath := filepath.Join(turnDir, "change-metadata.jsonl")
	
	file, err := os.Create(jsonlPath)
	if err != nil {
		return fmt.Errorf("failed to create change-metadata.jsonl: %w", err)
	}
	defer file.Close()

	for _, metaFilePath := range metaFiles {
		gscData, err := readAndParseMetaFile(metaFilePath)
		if err != nil {
			// Log warning but continue processing other files
			fmt.Fprintf(os.Stderr, "WARNING: Failed to read %s for JSONL aggregation: %v\n", metaFilePath, err)
			continue
		}

		// Marshal to JSON (compact format for JSONL)
		data, err := json.Marshal(gscData)
		if err != nil {
			fmt.Fprintf(os.Stderr, "WARNING: Failed to marshal %s for JSONL aggregation: %v\n", metaFilePath, err)
			continue
		}

		// Write line with newline
		if _, err := file.Write(append(data, '\n')); err != nil {
			return fmt.Errorf("failed to write to change-metadata.jsonl: %w", err)
		}
	}

	return nil
}
